// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.5
// source: combat.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 战斗-敌人组-敌人数量-范围
type CombatEnemyGroupEnemyCountRange int32

const (
	CombatEnemyGroupEnemyCountRange_CombatEnemyGroupEnemyCountRange_Unknow CombatEnemyGroupEnemyCountRange = 0  // 未知参数
	CombatEnemyGroupEnemyCountRange_CombatEnemyGroupEnemyCountRange_Min    CombatEnemyGroupEnemyCountRange = 1  // 敌人组-敌人数量最小值
	CombatEnemyGroupEnemyCountRange_CombatEnemyGroupEnemyCountRange_Max    CombatEnemyGroupEnemyCountRange = 10 // 敌人组-敌人数量最大值
)

// Enum value maps for CombatEnemyGroupEnemyCountRange.
var (
	CombatEnemyGroupEnemyCountRange_name = map[int32]string{
		0:  "CombatEnemyGroupEnemyCountRange_Unknow",
		1:  "CombatEnemyGroupEnemyCountRange_Min",
		10: "CombatEnemyGroupEnemyCountRange_Max",
	}
	CombatEnemyGroupEnemyCountRange_value = map[string]int32{
		"CombatEnemyGroupEnemyCountRange_Unknow": 0,
		"CombatEnemyGroupEnemyCountRange_Min":    1,
		"CombatEnemyGroupEnemyCountRange_Max":    10,
	}
)

func (x CombatEnemyGroupEnemyCountRange) Enum() *CombatEnemyGroupEnemyCountRange {
	p := new(CombatEnemyGroupEnemyCountRange)
	*p = x
	return p
}

func (x CombatEnemyGroupEnemyCountRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatEnemyGroupEnemyCountRange) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[0].Descriptor()
}

func (CombatEnemyGroupEnemyCountRange) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[0]
}

func (x CombatEnemyGroupEnemyCountRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatEnemyGroupEnemyCountRange.Descriptor instead.
func (CombatEnemyGroupEnemyCountRange) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{0}
}

// 战斗-敌人组-宝宝概率-范围
type CombatEnemyGroupBabyRate int32

const (
	CombatEnemyGroupBabyRate_CombatEnemyGroupBabyRate_Min CombatEnemyGroupBabyRate = 0      // 敌人组-宝宝概率最小值
	CombatEnemyGroupBabyRate_CombatEnemyGroupBabyRate_Max CombatEnemyGroupBabyRate = 100000 // 敌人组-宝宝概率最大值(十万分率,100000=100%)
)

// Enum value maps for CombatEnemyGroupBabyRate.
var (
	CombatEnemyGroupBabyRate_name = map[int32]string{
		0:      "CombatEnemyGroupBabyRate_Min",
		100000: "CombatEnemyGroupBabyRate_Max",
	}
	CombatEnemyGroupBabyRate_value = map[string]int32{
		"CombatEnemyGroupBabyRate_Min": 0,
		"CombatEnemyGroupBabyRate_Max": 100000,
	}
)

func (x CombatEnemyGroupBabyRate) Enum() *CombatEnemyGroupBabyRate {
	p := new(CombatEnemyGroupBabyRate)
	*p = x
	return p
}

func (x CombatEnemyGroupBabyRate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombatEnemyGroupBabyRate) Descriptor() protoreflect.EnumDescriptor {
	return file_combat_proto_enumTypes[1].Descriptor()
}

func (CombatEnemyGroupBabyRate) Type() protoreflect.EnumType {
	return &file_combat_proto_enumTypes[1]
}

func (x CombatEnemyGroupBabyRate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombatEnemyGroupBabyRate.Descriptor instead.
func (CombatEnemyGroupBabyRate) EnumDescriptor() ([]byte, []int) {
	return file_combat_proto_rawDescGZIP(), []int{1}
}

var File_combat_proto protoreflect.FileDescriptor

var file_combat_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x2a, 0x9f, 0x01, 0x0a, 0x1f, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65,
	0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x26, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74,
	0x45, 0x6e, 0x65, 0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77,
	0x10, 0x00, 0x12, 0x27, 0x0a, 0x23, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x4d, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x27, 0x0a, 0x23, 0x43,
	0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45,
	0x6e, 0x65, 0x6d, 0x79, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x4d,
	0x61, 0x78, 0x10, 0x0a, 0x2a, 0x60, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e,
	0x65, 0x6d, 0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x62, 0x79, 0x52, 0x61, 0x74, 0x65,
	0x12, 0x20, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d, 0x79, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x62, 0x79, 0x52, 0x61, 0x74, 0x65, 0x5f, 0x4d, 0x69, 0x6e,
	0x10, 0x00, 0x12, 0x22, 0x0a, 0x1c, 0x43, 0x6f, 0x6d, 0x62, 0x61, 0x74, 0x45, 0x6e, 0x65, 0x6d,
	0x79, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x42, 0x61, 0x62, 0x79, 0x52, 0x61, 0x74, 0x65, 0x5f, 0x4d,
	0x61, 0x78, 0x10, 0xa0, 0x8d, 0x06, 0x42, 0x10, 0x5a, 0x0e, 0x73, 0x61, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_combat_proto_rawDescOnce sync.Once
	file_combat_proto_rawDescData = file_combat_proto_rawDesc
)

func file_combat_proto_rawDescGZIP() []byte {
	file_combat_proto_rawDescOnce.Do(func() {
		file_combat_proto_rawDescData = protoimpl.X.CompressGZIP(file_combat_proto_rawDescData)
	})
	return file_combat_proto_rawDescData
}

var file_combat_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_combat_proto_goTypes = []any{
	(CombatEnemyGroupEnemyCountRange)(0), // 0: pb.CombatEnemyGroupEnemyCountRange
	(CombatEnemyGroupBabyRate)(0),        // 1: pb.CombatEnemyGroupBabyRate
}
var file_combat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_combat_proto_init() }
func file_combat_proto_init() {
	if File_combat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_combat_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_combat_proto_goTypes,
		DependencyIndexes: file_combat_proto_depIdxs,
		EnumInfos:         file_combat_proto_enumTypes,
	}.Build()
	File_combat_proto = out.File
	file_combat_proto_rawDesc = nil
	file_combat_proto_goTypes = nil
	file_combat_proto_depIdxs = nil
}
