// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.0
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色朝向
type RoleDirection int32

const (
	RoleDirection_RoleDirection_Unknow    RoleDirection = 0 // 未知方向
	RoleDirection_RoleDirection_Up        RoleDirection = 1 // 上
	RoleDirection_RoleDirection_UpRight   RoleDirection = 2 // 右上
	RoleDirection_RoleDirection_Right     RoleDirection = 3 // 右
	RoleDirection_RoleDirection_DownRight RoleDirection = 4 // 右下
	RoleDirection_RoleDirection_Down      RoleDirection = 5 // 下
	RoleDirection_RoleDirection_DownLeft  RoleDirection = 6 // 左下
	RoleDirection_RoleDirection_Left      RoleDirection = 7 // 左
	RoleDirection_RoleDirection_UpLeft    RoleDirection = 8 // 左上
	RoleDirection_RoleDirection_Max       RoleDirection = 9 // 方向最大值
)

// Enum value maps for RoleDirection.
var (
	RoleDirection_name = map[int32]string{
		0: "RoleDirection_Unknow",
		1: "RoleDirection_Up",
		2: "RoleDirection_UpRight",
		3: "RoleDirection_Right",
		4: "RoleDirection_DownRight",
		5: "RoleDirection_Down",
		6: "RoleDirection_DownLeft",
		7: "RoleDirection_Left",
		8: "RoleDirection_UpLeft",
		9: "RoleDirection_Max",
	}
	RoleDirection_value = map[string]int32{
		"RoleDirection_Unknow":    0,
		"RoleDirection_Up":        1,
		"RoleDirection_UpRight":   2,
		"RoleDirection_Right":     3,
		"RoleDirection_DownRight": 4,
		"RoleDirection_Down":      5,
		"RoleDirection_DownLeft":  6,
		"RoleDirection_Left":      7,
		"RoleDirection_UpLeft":    8,
		"RoleDirection_Max":       9,
	}
)

func (x RoleDirection) Enum() *RoleDirection {
	p := new(RoleDirection)
	*p = x
	return p
}

func (x RoleDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (RoleDirection) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x RoleDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleDirection.Descriptor instead.
func (RoleDirection) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type RoleAction int32

const (
	RoleAction_RoleAction_Unknow RoleAction = 0 // 未知动作
	RoleAction_RoleAction_Idle   RoleAction = 1 // 待机
	RoleAction_RoleAction_Stand  RoleAction = 2 // 站立
	RoleAction_RoleAction_Move   RoleAction = 3 // 移动
	RoleAction_RoleAction_Attack RoleAction = 4 // 攻击
	RoleAction_RoleAction_Hurt   RoleAction = 5 // 受伤
	RoleAction_RoleAction_Die    RoleAction = 6 // 死亡
	RoleAction_RoleAction_Max    RoleAction = 7 // 动作最大值
)

// Enum value maps for RoleAction.
var (
	RoleAction_name = map[int32]string{
		0: "RoleAction_Unknow",
		1: "RoleAction_Idle",
		2: "RoleAction_Stand",
		3: "RoleAction_Move",
		4: "RoleAction_Attack",
		5: "RoleAction_Hurt",
		6: "RoleAction_Die",
		7: "RoleAction_Max",
	}
	RoleAction_value = map[string]int32{
		"RoleAction_Unknow": 0,
		"RoleAction_Idle":   1,
		"RoleAction_Stand":  2,
		"RoleAction_Move":   3,
		"RoleAction_Attack": 4,
		"RoleAction_Hurt":   5,
		"RoleAction_Die":    6,
		"RoleAction_Max":    7,
	}
)

func (x RoleAction) Enum() *RoleAction {
	p := new(RoleAction)
	*p = x
	return p
}

func (x RoleAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleAction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (RoleAction) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x RoleAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleAction.Descriptor instead.
func (RoleAction) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// 宠物-稀有度
type PetRarity int32

const (
	PetRarity_Rarity_Unknow    PetRarity = 0 // 未知
	PetRarity_Rarity_Common    PetRarity = 1 // 普通-白色
	PetRarity_Rarity_Rare      PetRarity = 2 // 稀有-绿色
	PetRarity_Rarity_Epic      PetRarity = 3 // 史诗-紫色
	PetRarity_Rarity_Legendary PetRarity = 4 // 传说-橙色
	PetRarity_Rarity_Mythic    PetRarity = 5 // 神话-红色
	PetRarity_Rarity_Max       PetRarity = 6 // 稀有度最大值
)

// Enum value maps for PetRarity.
var (
	PetRarity_name = map[int32]string{
		0: "Rarity_Unknow",
		1: "Rarity_Common",
		2: "Rarity_Rare",
		3: "Rarity_Epic",
		4: "Rarity_Legendary",
		5: "Rarity_Mythic",
		6: "Rarity_Max",
	}
	PetRarity_value = map[string]int32{
		"Rarity_Unknow":    0,
		"Rarity_Common":    1,
		"Rarity_Rare":      2,
		"Rarity_Epic":      3,
		"Rarity_Legendary": 4,
		"Rarity_Mythic":    5,
		"Rarity_Max":       6,
	}
)

func (x PetRarity) Enum() *PetRarity {
	p := new(PetRarity)
	*p = x
	return p
}

func (x PetRarity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PetRarity) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (PetRarity) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x PetRarity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PetRarity.Descriptor instead.
func (PetRarity) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

// 键值对 key:uint32 value:uint32
type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *KV) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// 矩形
type Rect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos    *Point `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`        // 位置
	Width  uint32 `protobuf:"varint,3,opt,name=Width,proto3" json:"Width,omitempty"`   // 宽度
	Height uint32 `protobuf:"varint,4,opt,name=Height,proto3" json:"Height,omitempty"` // 高度
}

func (x *Rect) Reset() {
	*x = Rect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *Rect) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Rect) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 图像
type Image struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  uint32 `protobuf:"varint,2,opt,name=Width,proto3" json:"Width,omitempty"`   // 宽度
	Height uint32 `protobuf:"varint,3,opt,name=Height,proto3" json:"Height,omitempty"` // 高度
}

func (x *Image) Reset() {
	*x = Image{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Image) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Image) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

// 坐标点
type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=X,proto3" json:"X,omitempty"` // X坐标
	Y uint32 `protobuf:"varint,2,opt,name=Y,proto3" json:"Y,omitempty"` // Y坐标
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *Point) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x2c, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x51, 0x0a, 0x04, 0x52, 0x65, 0x63, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x48, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x22, 0x35, 0x0a, 0x05, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x57, 0x69, 0x64,
	0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01,
	0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x59, 0x2a,
	0x8d, 0x02, 0x0a, 0x0d, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x52,
	0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x55, 0x70, 0x10,
	0x01, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x55, 0x70, 0x52, 0x69, 0x67, 0x68, 0x74, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13,
	0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x52, 0x69,
	0x67, 0x68, 0x74, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x44, 0x6f, 0x77, 0x6e, 0x52, 0x69, 0x67, 0x68, 0x74,
	0x10, 0x04, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x44, 0x6f, 0x77, 0x6e, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x52, 0x6f,
	0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x44, 0x6f, 0x77, 0x6e,
	0x4c, 0x65, 0x66, 0x74, 0x10, 0x06, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x4c, 0x65, 0x66, 0x74, 0x10, 0x07, 0x12, 0x18,
	0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x55, 0x70, 0x4c, 0x65, 0x66, 0x74, 0x10, 0x08, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x09, 0x2a,
	0xb7, 0x01, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15,
	0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x55, 0x6e, 0x6b,
	0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x49, 0x64, 0x6c, 0x65, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x52, 0x6f,
	0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x10, 0x02,
	0x12, 0x13, 0x0a, 0x0f, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x4d,
	0x6f, 0x76, 0x65, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x41, 0x74, 0x74, 0x61, 0x63, 0x6b, 0x10, 0x04, 0x12, 0x13, 0x0a, 0x0f,
	0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x48, 0x75, 0x72, 0x74, 0x10,
	0x05, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x44, 0x69, 0x65, 0x10, 0x06, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x07, 0x2a, 0x8c, 0x01, 0x0a, 0x09, 0x50, 0x65,
	0x74, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x61, 0x72, 0x69, 0x74,
	0x79, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x0f, 0x0a,
	0x0b, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x52, 0x61, 0x72, 0x65, 0x10, 0x02, 0x12, 0x0f,
	0x0a, 0x0b, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x45, 0x70, 0x69, 0x63, 0x10, 0x03, 0x12,
	0x14, 0x0a, 0x10, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f, 0x4c, 0x65, 0x67, 0x65, 0x6e, 0x64,
	0x61, 0x72, 0x79, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x61, 0x72, 0x69, 0x74, 0x79, 0x5f,
	0x4d, 0x79, 0x74, 0x68, 0x69, 0x63, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x06, 0x42, 0x10, 0x5a, 0x0e, 0x73, 0x61, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_proto_goTypes = []any{
	(RoleDirection)(0), // 0: pb.RoleDirection
	(RoleAction)(0),    // 1: pb.RoleAction
	(PetRarity)(0),     // 2: pb.PetRarity
	(*KV)(nil),         // 3: pb.KV
	(*Rect)(nil),       // 4: pb.Rect
	(*Image)(nil),      // 5: pb.Image
	(*Point)(nil),      // 6: pb.Point
}
var file_common_proto_depIdxs = []int32{
	6, // 0: pb.Rect.Pos:type_name -> pb.Point
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Rect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Image); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
