// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.5
// source: weapon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 角色-武器类型
type RoleWeaponType int32

const (
	RoleWeaponType_RoleWeaponType_Unknow    RoleWeaponType = 0 // 未知武器类型
	RoleWeaponType_RoleWeaponType_BareHands RoleWeaponType = 1 // 赤手空拳
	RoleWeaponType_RoleWeaponType_Axe       RoleWeaponType = 2 // 斧
	RoleWeaponType_RoleWeaponType_Stick     RoleWeaponType = 3 // 棍
	RoleWeaponType_RoleWeaponType_Spear     RoleWeaponType = 4 // 矛
	RoleWeaponType_RoleWeaponType_Claw      RoleWeaponType = 5 // 爪
	RoleWeaponType_RoleWeaponType_Bow       RoleWeaponType = 6 // 弓
	RoleWeaponType_RoleWeaponType_Staff     RoleWeaponType = 7 // 杖
	RoleWeaponType_RoleWeaponType_Max       RoleWeaponType = 8 // 武器类型-最大值
)

// Enum value maps for RoleWeaponType.
var (
	RoleWeaponType_name = map[int32]string{
		0: "RoleWeaponType_Unknow",
		1: "RoleWeaponType_BareHands",
		2: "RoleWeaponType_Axe",
		3: "RoleWeaponType_Stick",
		4: "RoleWeaponType_Spear",
		5: "RoleWeaponType_Claw",
		6: "RoleWeaponType_Bow",
		7: "RoleWeaponType_Staff",
		8: "RoleWeaponType_Max",
	}
	RoleWeaponType_value = map[string]int32{
		"RoleWeaponType_Unknow":    0,
		"RoleWeaponType_BareHands": 1,
		"RoleWeaponType_Axe":       2,
		"RoleWeaponType_Stick":     3,
		"RoleWeaponType_Spear":     4,
		"RoleWeaponType_Claw":      5,
		"RoleWeaponType_Bow":       6,
		"RoleWeaponType_Staff":     7,
		"RoleWeaponType_Max":       8,
	}
)

func (x RoleWeaponType) Enum() *RoleWeaponType {
	p := new(RoleWeaponType)
	*p = x
	return p
}

func (x RoleWeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleWeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_weapon_proto_enumTypes[0].Descriptor()
}

func (RoleWeaponType) Type() protoreflect.EnumType {
	return &file_weapon_proto_enumTypes[0]
}

func (x RoleWeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleWeaponType.Descriptor instead.
func (RoleWeaponType) EnumDescriptor() ([]byte, []int) {
	return file_weapon_proto_rawDescGZIP(), []int{0}
}

var File_weapon_proto protoreflect.FileDescriptor

var file_weapon_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x77, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x2a, 0xf8, 0x01, 0x0a, 0x0e, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00,
	0x12, 0x1c, 0x0a, 0x18, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x42, 0x61, 0x72, 0x65, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x10, 0x01, 0x12, 0x16,
	0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x5f, 0x41, 0x78, 0x65, 0x10, 0x02, 0x12, 0x18, 0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65,
	0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x53, 0x74, 0x69, 0x63, 0x6b, 0x10, 0x03,
	0x12, 0x18, 0x0a, 0x14, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79,
	0x70, 0x65, 0x5f, 0x53, 0x70, 0x65, 0x61, 0x72, 0x10, 0x04, 0x12, 0x17, 0x0a, 0x13, 0x52, 0x6f,
	0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x43, 0x6c, 0x61,
	0x77, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x42, 0x6f, 0x77, 0x10, 0x06, 0x12, 0x18, 0x0a, 0x14, 0x52,
	0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61, 0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x53, 0x74,
	0x61, 0x66, 0x66, 0x10, 0x07, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x6f, 0x6c, 0x65, 0x57, 0x65, 0x61,
	0x70, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x78, 0x10, 0x08, 0x42, 0x10, 0x5a,
	0x0e, 0x73, 0x61, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_weapon_proto_rawDescOnce sync.Once
	file_weapon_proto_rawDescData = file_weapon_proto_rawDesc
)

func file_weapon_proto_rawDescGZIP() []byte {
	file_weapon_proto_rawDescOnce.Do(func() {
		file_weapon_proto_rawDescData = protoimpl.X.CompressGZIP(file_weapon_proto_rawDescData)
	})
	return file_weapon_proto_rawDescData
}

var file_weapon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_weapon_proto_goTypes = []any{
	(RoleWeaponType)(0), // 0: pb.RoleWeaponType
}
var file_weapon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_weapon_proto_init() }
func file_weapon_proto_init() {
	if File_weapon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_weapon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_weapon_proto_goTypes,
		DependencyIndexes: file_weapon_proto_depIdxs,
		EnumInfos:         file_weapon_proto_enumTypes,
	}.Build()
	File_weapon_proto = out.File
	file_weapon_proto_rawDesc = nil
	file_weapon_proto_goTypes = nil
	file_weapon_proto_depIdxs = nil
}
