// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.5
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 资源类型
type ResType int32

const (
	ResType_ResType_Unknow ResType = 0 // 无
	ResType_ResType_Role   ResType = 1 // 资源类型-角色
	ResType_ResType_Map    ResType = 2 // 资源类型-地图
	ResType_ResType_Item   ResType = 3 // 资源类型-物品
)

// Enum value maps for ResType.
var (
	ResType_name = map[int32]string{
		0: "ResType_Unknow",
		1: "ResType_Role",
		2: "ResType_Map",
		3: "ResType_Item",
	}
	ResType_value = map[string]int32{
		"ResType_Unknow": 0,
		"ResType_Role":   1,
		"ResType_Map":    2,
		"ResType_Item":   3,
	}
)

func (x ResType) Enum() *ResType {
	p := new(ResType)
	*p = x
	return p
}

func (x ResType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ResType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ResType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResType.Descriptor instead.
func (ResType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// 元素类型
type ElementalType int32

const (
	ElementalType_ElementalType_Unknow ElementalType = 0 // 无
	ElementalType_ElementalType_Earth  ElementalType = 1 // 元素类型-土
	ElementalType_ElementalType_Water  ElementalType = 2 // 元素类型-水
	ElementalType_ElementalType_Fire   ElementalType = 3 // 元素类型-火
	ElementalType_ElementalType_Wind   ElementalType = 4 // 元素类型-风
)

// Enum value maps for ElementalType.
var (
	ElementalType_name = map[int32]string{
		0: "ElementalType_Unknow",
		1: "ElementalType_Earth",
		2: "ElementalType_Water",
		3: "ElementalType_Fire",
		4: "ElementalType_Wind",
	}
	ElementalType_value = map[string]int32{
		"ElementalType_Unknow": 0,
		"ElementalType_Earth":  1,
		"ElementalType_Water":  2,
		"ElementalType_Fire":   3,
		"ElementalType_Wind":   4,
	}
)

func (x ElementalType) Enum() *ElementalType {
	p := new(ElementalType)
	*p = x
	return p
}

func (x ElementalType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ElementalType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (ElementalType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x ElementalType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ElementalType.Descriptor instead.
func (ElementalType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type KV struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value uint32 `protobuf:"varint,2,opt,name=Value,proto3" json:"Value,omitempty"`
}

func (x *KV) Reset() {
	*x = KV{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KV) ProtoMessage() {}

func (x *KV) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KV.ProtoReflect.Descriptor instead.
func (*KV) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *KV) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *KV) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x2c, 0x0a, 0x02, 0x4b, 0x56, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x4b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x2a, 0x52, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x52,
	0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12,
	0x10, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x52, 0x6f, 0x6c, 0x65, 0x10,
	0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x4d, 0x61, 0x70,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x49, 0x74,
	0x65, 0x6d, 0x10, 0x03, 0x2a, 0x8b, 0x01, 0x0a, 0x0d, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00,
	0x12, 0x17, 0x0a, 0x13, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x5f, 0x45, 0x61, 0x72, 0x74, 0x68, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13, 0x45, 0x6c, 0x65,
	0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x61, 0x74, 0x65, 0x72,
	0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x54,
	0x79, 0x70, 0x65, 0x5f, 0x46, 0x69, 0x72, 0x65, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x5f, 0x57, 0x69, 0x6e, 0x64,
	0x10, 0x04, 0x42, 0x10, 0x5a, 0x0e, 0x73, 0x61, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_proto_goTypes = []any{
	(ResType)(0),       // 0: pb.ResType
	(ElementalType)(0), // 1: pb.ElementalType
	(*KV)(nil),         // 2: pb.KV
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KV); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
