syntax="proto3";

package pb;

option go_package = "saClient/proto";

// 资产-分段 uint32 AssetID 最大值为: 4294,967295
// 采用分段编码方式, 定义不同类型资产ID范围
// A[1,4293] B[0,999999]

// ⚠️ 实际上 enum 出来的是 int32 所以最大值为: 2147,483647
// A[1,2146] B[0,999999]

// 资产类型
enum AssetType {
  AssetType_RoleBase = 0; // 角色基础 [1,1000000]
  AssetType_Role = 1; // 角色 [1000001,1999999]
  AssetType_Map = 2; // 地图 [2000001,2999999]
  AssetType_Item = 3; // 物品 [3000001,3999999]
  AssetType_Pet = 4; // 宠物 [4000001,4999999]
  AssetType_NPC = 5; // NPC [5000001,5999999]
}

// 资产ID-角色基础 [1,1000000]
enum AssetIDRoleBase {
  AssetIDRoleBase_Unknow = 0; // 角色基础-未知

  AssetIDRoleBase_Exp = 1; // 角色基础-经验值
  AssetIDRoleBase_HP = 2; // 角色基础-生命值
  AssetIDRoleBase_MP = 3; // 角色基础-魔法值
  AssetIDRoleBase_CreateTimestamp = 4; // 角色基础-创建时间戳
  AssetIDRoleBase_LastLoginTimestamp = 5; // 角色基础-上次登录时间戳
  AssetIDRoleBase_LastLogoutTimestamp = 6; // 角色基础-上次登出时间戳
  AssetIDRoleBase_MapID = 7; // 角色基础-所在地图ID
  AssetIDRoleBase_X = 8; // 角色当前位置X
  AssetIDRoleBase_Y = 9; // 角色当前位置Y
  AssetIDRoleBase_Direction = 10; // 角色当前位置朝向
  AssetIDRoleBase_Pose = 11; // 角色基础-姿势 0:站立 1:坐下

  AssetIDRoleBase_ElementalEarth = 101; // 角色基础-元素属性-土
  AssetIDRoleBase_ElementalWater = 102; // 角色基础-元素属性-水
  AssetIDRoleBase_ElementalFire = 103; // 角色基础-元素属性-火
  AssetIDRoleBase_ElementalWind = 104; // 角色基础-元素属性-风

  AssetIDRoleBase_BasicAttack = 201; // 角色基础--攻
  AssetIDRoleBase_BasicDefensePoint = 202; // 角色基础-防
  AssetIDRoleBase_BasicAgility = 203; // 角色基础-敏
  AssetIDRoleBase_BasicHP = 204; // 角色基础-生命
}

// 资产ID-角色 [1000001,1999999]
enum AssetIDRole {
  AssetIDRole_Unknow = 0; // 角色-未知

  AssetIDRole_Male_Leon_Red = 1000101; // 角色-男性-里昂-红 带坚毅感，适合战士、领头类角色
  AssetIDRole_Male_Allen_Blue = 1000201; // 角色-男性-艾伦-蓝 经典百搭，适合正直型角色（如骑士、主力输出）
  AssetIDRole_Male_Kai_Green = 1000301; // 角色-男性-凯-绿 简短有力，适配敏捷型角色（如刺客、游侠）
  AssetIDRole_Male_Ian_Purple = 1000401; // 角色-男性-伊恩-紫 温和中带沉稳，适配法师、辅助型角色
  AssetIDRole_Male_Colin_Yellow = 1000501; // 角色-男性-科林-黄 轻快灵动，适合斥候、年轻冒险者
  AssetIDRole_Male_Jasper_White = 1000601; // 角色-男性-贾斯珀-白 带复古奇幻感，适配牧师、术士类角色
  AssetIDRole_Male_Marcus_Black = 1000701; // 角色-男性-马库斯-黑 厚重有气场，适合坦克、队长类角色
  AssetIDRole_Male_Samuel_Silver = 1000801; // 角色-男性-塞缪尔-银 温润可靠，适配治疗、后勤类角色
  AssetIDRole_Male_Toby_Orange = 1000901; // 角色-男性-托比-橙 活泼亲民，适合新手引导、伙伴类角色

  AssetIDRole_Female_Lilian_Pink = 1500101; // 角色-女性-莉莉安-粉 柔美清新，适合牧师、治疗型角色
  AssetIDRole_Female_Ella_Red = 1500201; // 角色-女性-艾拉-红 简洁灵动，适配敏捷型刺客、游侠
  AssetIDRole_Female_Evelyn_Purple = 1500301; // 角色-女性-伊芙琳-紫 优雅带神秘感，适合法师、术士类角色
  AssetIDRole_Female_Sophia_Blue = 1500401; // 角色-女性-索菲娅-蓝 温润知性，适配辅助、策略型角色
  AssetIDRole_Female_Claire_Silver = 1500501; // 角色-女性-克莱尔-银 干练利落，适合战士、女骑士类角色
  AssetIDRole_Female_Mila_Yellow = 1500601; // 角色-女性-米拉-黄 轻快可爱，适合新手伙伴、俏皮型角色
  AssetIDRole_Female_Nora_Gold = 1500701; // 角色-女性-诺拉-金 沉稳大气，适配领主、资深冒险者
  AssetIDRole_Female_Sierra_Green = 1500801; // 角色-女性-塞拉-绿 带自然感，适合德鲁伊、森林游侠
  AssetIDRole_Female_Valerie_White = 1500901; // 角色-女性-瓦莱丽-白 坚毅有力量，适合近战输出、守护型角色
}


